Search.appendIndex(
    [
                {
            "fqsen": "\\Octris\\Sqlbuilder\\AbstractDialect",
            "name": "AbstractDialect",
            "summary": "SQL\u0020Dialects\u0020base\u0020class.",
            "url": "classes/Octris-Sqlbuilder-AbstractDialect.html"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\AbstractDialect\u003A\u003AgetLimitString\u0028\u0029",
            "name": "getLimitString",
            "summary": "Return\u0020string\u0020for\u0020limiting\u0020result.",
            "url": "classes/Octris-Sqlbuilder-AbstractDialect.html#method_getLimitString"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\AbstractDialect\u003A\u003AresolveParameter\u0028\u0029",
            "name": "resolveParameter",
            "summary": "Resolve\u0020query\u0020parameter.",
            "url": "classes/Octris-Sqlbuilder-AbstractDialect.html#method_resolveParameter"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Clauses",
            "name": "Clauses",
            "summary": "SQL\u0020builder\u0020clauses.",
            "url": "classes/Octris-Sqlbuilder-Clauses.html"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Clauses\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Octris-Sqlbuilder-Clauses.html#method___construct"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Clauses\u003A\u003AresolveClauses\u0028\u0029",
            "name": "resolveClauses",
            "summary": "Resolve\u0020clauses.",
            "url": "classes/Octris-Sqlbuilder-Clauses.html#method_resolveClauses"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Clauses\u003A\u003AaddClause\u0028\u0029",
            "name": "addClause",
            "summary": "Add\u0020a\u0020clause\u0020to\u0020the\u0020list\u0020of\u0020clauses.",
            "url": "classes/Octris-Sqlbuilder-Clauses.html#method_addClause"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Clauses\u003A\u003A\u0024joiner",
            "name": "joiner",
            "summary": "String\u0020to\u0020use\u0020for\u0020joining\u0020multiple\u0020clauses.",
            "url": "classes/Octris-Sqlbuilder-Clauses.html#property_joiner"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Clauses\u003A\u003A\u0024prefix",
            "name": "prefix",
            "summary": "Prefix\u0020string\u0020for\u0020joined\u0020clauses.",
            "url": "classes/Octris-Sqlbuilder-Clauses.html#property_prefix"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Clauses\u003A\u003A\u0024postfix",
            "name": "postfix",
            "summary": "Postfix\u0020string\u0020for\u0020joined\u0020clauses.",
            "url": "classes/Octris-Sqlbuilder-Clauses.html#property_postfix"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Clauses\u003A\u003A\u0024clauses",
            "name": "clauses",
            "summary": "Clauses.",
            "url": "classes/Octris-Sqlbuilder-Clauses.html#property_clauses"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Clauses\u003A\u003A\u0024parameters",
            "name": "parameters",
            "summary": "Parameters.",
            "url": "classes/Octris-Sqlbuilder-Clauses.html#property_parameters"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Dialect\\Mysql",
            "name": "Mysql",
            "summary": "MySQL\u0020dialect.",
            "url": "classes/Octris-Sqlbuilder-Dialect-Mysql.html"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Dialect\\Mysql\u003A\u003AgetLimitString\u0028\u0029",
            "name": "getLimitString",
            "summary": "Return\u0020string\u0020for\u0020limiting\u0020result.",
            "url": "classes/Octris-Sqlbuilder-Dialect-Mysql.html#method_getLimitString"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Dialect\\Mysql\u003A\u003AresolveParameter\u0028\u0029",
            "name": "resolveParameter",
            "summary": "Resolve\u0020query\u0020parameter.",
            "url": "classes/Octris-Sqlbuilder-Dialect-Mysql.html#method_resolveParameter"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Template",
            "name": "Template",
            "summary": "SQL\u0020builder\u0020template\u0020class.",
            "url": "classes/Octris-Sqlbuilder-Template.html"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Template\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Octris-Sqlbuilder-Template.html#method___construct"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Template\u003A\u003AresolveSql\u0028\u0029",
            "name": "resolveSql",
            "summary": "Resolve\u0020SQL\u0020statement.",
            "url": "classes/Octris-Sqlbuilder-Template.html#method_resolveSql"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Template\u003A\u003A\u0024builder",
            "name": "builder",
            "summary": "SQL\u0020builder\u0020instance.",
            "url": "classes/Octris-Sqlbuilder-Template.html#property_builder"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Template\u003A\u003A\u0024sql",
            "name": "sql",
            "summary": "SQL\u0020template.",
            "url": "classes/Octris-Sqlbuilder-Template.html#property_sql"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder",
            "name": "Sqlbuilder",
            "summary": "SQL\u0020builder.",
            "url": "classes/Octris-Sqlbuilder.html"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor.",
            "url": "classes/Octris-Sqlbuilder.html#method___construct"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AresolveSnippet\u0028\u0029",
            "name": "resolveSnippet",
            "summary": "Resolve\u0020template\u0020snippet.",
            "url": "classes/Octris-Sqlbuilder.html#method_resolveSnippet"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AresolveParameter\u0028\u0029",
            "name": "resolveParameter",
            "summary": "Resolve\u0020query\u0020parameter.",
            "url": "classes/Octris-Sqlbuilder.html#method_resolveParameter"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddSnippet\u0028\u0029",
            "name": "addSnippet",
            "summary": "Add\u0020a\u0020textual\u0020template\u0020snippet.",
            "url": "classes/Octris-Sqlbuilder.html#method_addSnippet"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddTemplate\u0028\u0029",
            "name": "addTemplate",
            "summary": "Add\u0020a\u0020template\u0020to\u0020the\u0020builder\u0020instance.",
            "url": "classes/Octris-Sqlbuilder.html#method_addTemplate"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddClause\u0028\u0029",
            "name": "addClause",
            "summary": "Add\u0020clause.",
            "url": "classes/Octris-Sqlbuilder.html#method_addClause"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddColumn\u0028\u0029",
            "name": "addColumn",
            "summary": "Columns\u0020for\u0020eg.\u003A\u0020INSERT\/UPDATE",
            "url": "classes/Octris-Sqlbuilder.html#method_addColumn"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddInnerJoin\u0028\u0029",
            "name": "addInnerJoin",
            "summary": "Add\u0020an\u0020\u0027inner\u0020join\u0027\u0020clause.",
            "url": "classes/Octris-Sqlbuilder.html#method_addInnerJoin"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddJoin\u0028\u0029",
            "name": "addJoin",
            "summary": "Add\u0020an\u0020\u0027join\u0027\u0020clause\u0020\u0028alias\u0020for\u0020\u0027inner\u0020join\u0027\u0029.",
            "url": "classes/Octris-Sqlbuilder.html#method_addJoin"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddLeftJoin\u0028\u0029",
            "name": "addLeftJoin",
            "summary": "Add\u0020a\u0020\u0027left\u0020join\u0027\u0020clause.",
            "url": "classes/Octris-Sqlbuilder.html#method_addLeftJoin"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddRightJoin\u0028\u0029",
            "name": "addRightJoin",
            "summary": "Add\u0020a\u0020\u0027right\u0020join\u0027\u0020clause.",
            "url": "classes/Octris-Sqlbuilder.html#method_addRightJoin"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddWhere\u0028\u0029",
            "name": "addWhere",
            "summary": "Add\u0020an\u0020\u0027AND\u0027\u0020condition.\u0020This\u0020method\u0020is\u0020an\u0020alias\u0020for\u0020\u0022addAndWhere\u0022.",
            "url": "classes/Octris-Sqlbuilder.html#method_addWhere"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddAndWhere\u0028\u0029",
            "name": "addAndWhere",
            "summary": "Add\u0020an\u0020\u0027AND\u0027\u0020condition.",
            "url": "classes/Octris-Sqlbuilder.html#method_addAndWhere"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddOrWhere\u0028\u0029",
            "name": "addOrWhere",
            "summary": "Add\u0020an\u0020\u0027OR\u0027\u0020condition.",
            "url": "classes/Octris-Sqlbuilder.html#method_addOrWhere"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddOrderBy\u0028\u0029",
            "name": "addOrderBy",
            "summary": "Add\u0020an\u0020\u0027order\u0020by\u0027\u0020clause.",
            "url": "classes/Octris-Sqlbuilder.html#method_addOrderBy"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddGroupBy\u0028\u0029",
            "name": "addGroupBy",
            "summary": "Add\u0020a\u0020\u0027group\u0020by\u0027\u0020clause.",
            "url": "classes/Octris-Sqlbuilder.html#method_addGroupBy"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddHaving\u0028\u0029",
            "name": "addHaving",
            "summary": "Add\u0020a\u0020\u0027having\u0027\u0020clause.",
            "url": "classes/Octris-Sqlbuilder.html#method_addHaving"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003AaddPaging\u0028\u0029",
            "name": "addPaging",
            "summary": "Add\u0020paging.",
            "url": "classes/Octris-Sqlbuilder.html#method_addPaging"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003A\u0024dialect",
            "name": "dialect",
            "summary": "Instance\u0020of\u0020SQL\u0020dialect\u0020class.",
            "url": "classes/Octris-Sqlbuilder.html#property_dialect"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003A\u0024snippets",
            "name": "snippets",
            "summary": "Template\u0020snippets.",
            "url": "classes/Octris-Sqlbuilder.html#property_snippets"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\u003A\u003A\u0024clauses",
            "name": "clauses",
            "summary": "Clauses.",
            "url": "classes/Octris-Sqlbuilder.html#property_clauses"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder",
            "name": "Sqlbuilder",
            "summary": "",
            "url": "namespaces/octris-sqlbuilder.html"
        },                {
            "fqsen": "\\Octris\\Sqlbuilder\\Dialect",
            "name": "Dialect",
            "summary": "",
            "url": "namespaces/octris-sqlbuilder-dialect.html"
        },                {
            "fqsen": "\\Octris",
            "name": "Octris",
            "summary": "",
            "url": "namespaces/octris.html"
        }            ]
);
